print("Hello You!")
print("What is your name?")
name = input("enter your name:")
print("HO HO HO, Who would want to name their child that.")
print("Well " + name + (", what year were you born?"))
yob = input("enter your year of birth:")
print("HO HO HO, i wouldnt be able to tell if you hadnt told me.")
print("And what month were you born?")
mob = input("enter your month of birth:")
print("no wonder you look like that. HOHOHO")
print("And on what day were you born?")
dob = input("enter your day of birth:")

bd = (yob, mob, dob)
print(bd)