print("wat is je naam?")
name = input("enter your name:")
print(name + "?" " mooie naam")
print("wil je je stats horen?")
input("Answer:")
import random
print("name:", name )
print("fight skill:", random.randint(0, 100))
print("brains:", random.randint(0, 100))
print("power:", random.randint(0, 0))
print("speed:", random.randint(0, 100))
print("agility:", random.randint(0, 100))
print("accuracy:", random.randint(0, 100))
print("weapon of choice:", random.choice(["Knife", "Sword",  "Axe", "Bow"]))
print("flight ability:", random.choice([True, False]))
